require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ImgToPdf' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNSyanImagePicker', :path => '../node_modules/react-native-syan-image-picker'

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'


  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNImageToPdf', :path => '../node_modules/react-native-image-to-pdf'

  pod 'react-native-slider', :path => '../node_modules/@react-native-community/slider'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNFileViewer', :path => '../node_modules/react-native-file-viewer'

  target 'ImgToPdfTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'ImgToPdf-tvOS' do
  # Pods for ImgToPdf-tvOS

  target 'ImgToPdf-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
